// automatically generated by the FlatBuffers compiler, do not modify

/**
 * Actions that can be performed.
 * Purely aesthetic; have no actual effect on simulation.
 * (Although the simulation may want to track the 'parents' of
 * particular robots.)
 * Actions may have 'targets', which are the units on which
 * the actions were performed.
 */
export enum Action{
  /**
   * Target: none
   */
  EXPLODE = 0,

  /**
   * Target: ID of robot spawned
   */
  SPAWN_UNIT = 1,

  /**
   * Target: location mined, x + y * width
   */
  MINE_URANIUM = 2,

  /**
   * Target: change in health (can be negative)
   */
  CHANGE_HEALTH = 3,

  /**
   * Dies due to an uncaught exception.
   * Target: none
   */
  DIE_EXCEPTION = 4
}

