// automatically generated by the FlatBuffers compiler, do not modify

/**
 * The possible types of things that can exist.
 * Note that bullets are not treated as bodies.
 */
export enum BodyType{
  ROBOT = 0
}

