// automatically generated by the FlatBuffers compiler, do not modify

package battlecode.schema;

/**
 * Actions that can be performed.
 * Purely aesthetic; have no actual effect on simulation.
 * (Although the simulation may want to track the 'parents' of
 * particular robots.)
 * Actions may have 'targets', which are the units on which
 * the actions were performed.
 */
public final class Action {
  private Action() { }
  /**
   * Target: none
   */
  public static final byte EXPLODE = 0;
  /**
   * Target: ID of robot spawned
   */
  public static final byte SPAWN_UNIT = 1;
  /**
   * Target: location mined, x + y * width
   */
  public static final byte MINE_URANIUM = 2;
  /**
   * Target: change in health (can be negative)
   */
  public static final byte CHANGE_HEALTH = 3;
  /**
   * Dies due to an uncaught exception.
   * Target: none
   */
  public static final byte DIE_EXCEPTION = 4;

  public static final String[] names = { "EXPLODE", "SPAWN_UNIT", "MINE_URANIUM", "CHANGE_HEALTH", "DIE_EXCEPTION", };

  public static String name(int e) { return names[e]; }
}

