// automatically generated by the FlatBuffers compiler, do not modify

package battlecode.schema;

/**
 * The possible types of things that can exist.
 * Note that bullets are not treated as bodies.
 */
public final class BodyType {
  private BodyType() { }
  public static final byte ROBOT = 0;

  public static final String[] names = { "ROBOT", };

  public static String name(int e) { return names[e]; }
}

